### PR TITLE
Refactor UserCommons table to use a better table definition

### LINKED ISSUE #41: BUG: Can't delete some commons
Recreation:

- Create some commons
- set date to current, set starting balance to 1, set cow price to 2, tick show leaderboard, degradation rate = 1, carry capacity = 100
- join commons
- set balance to 5
- try to delete

Likely is a result of joining the commons and attempting to delete after (db issue?)

### LINKED ISSUE #45: Refactor the UserCommons table
Right now, the UserCommons table has its own id field, but the code treats it as a one-to-one mapping between User and Commons. Refactoring the table is better practice, allows the database to take responsibility for data constraints, instead of this logic scattered througout the code.

This also may resolve a few bugs:
- If a user join 2 commons, and one commons is deleted, the other commons is also cascade deleted.
- On QA, deleting a commons sometimes gives a 500.

# Acceptance criteria
- UserCommons is should be keyed by (user_id, commons_id)
- Existing code handling data constraints now handled by the database is removed
- The proper cascading delete behavior occurs when a commons is deleted (all related userCommons are deleted, but nothing more)
- These operations are tested on QA, using a real database

### PR DESCRIPTION
**Pull request by GlassBricks**
In this PR, we refactor the UserCommons table to be properly represent a relationship between User and Commons.
This allows the database system to handle data constraints such as uniqueness, foreign key, and cascading delete, instead of this being handled in scattered logic in the code.

For more info, see #45, and the slack discussion.

- I also cleaned up code in places areas this affects.
- My autoformatter resets indentation to 4 spaces, which results in some very large diffs... it might be clearer to view this in an IDE instead of on github, which treats indentation separately
- I removed logic/tests that are no longer necessary:
   - Checking if userId or commonsId exists, from a userCommons; instead you can use `userCommons.getUser()` or `.getCommons()`

Closes #45

### CODE REVIEW

**Comment by GlassBricks** [comment]
Hmmm, despite tests, this is not working on QA

Edit: fixed below

**Comment by GlassBricks** [comment]
Fixed 500 response with `/api/commons/join` endpoint on QA

For the curious, I debugged this issue on QA (that didn't appear on local), by:
- checking logs on dokku -- seems to be an exception caused by JPA trying to save a UserCommons. Works on my local machine, so postgres is probably the culprit
- researching how to use postgres and spring boot on my local machine, creating a postgres db on my local machine, modifying `src/main/resources/application-development.properties` to connect to it
- Test -- issue reproduced
- Using the Intellij debugger, exception breakpoints, and some snooping into 3rd party libraries...

**Review by pconrad — APPROVED** [review]
LGTM... I will want to do some extensive testing on staff-qa since this touches so much code, but these look like really good refactorings, and I appreciate the time you put into it.

**Comment by pconrad** [comment]
This is good work.   We can take it a step further, as suggested in #52 , but for now, we can merge this.

**Pull request merged**
