### PR TITLE
Redesign play page UI

### LINKED ISSUE #39: Redesign the user commons page
Redesign the components of the farm stats column: photos, total wealth, and cow health.

Some things you could do to achieve this:

- [x] Centering Farm Stats: Center the farm stats column photos, total wealth, and cow health
- [x] Make key user statistics clear: Change the size of photos to be smaller and make text like total wealth bigger
- [x] Address ambiguous labels in the profits table, such as the unclear "Amount" column.

Part of #11

### PR DESCRIPTION
**Pull request by mfletcher2**
This PR changes the components of `PlayPage` such that:

- Large images are replaced with emojis
- Text is centered
- Buy/Sell buttons are different colors
- A progress bar representing cow health is added
- The profits table headers are more intuitive
- The profits table are displayed newest first by default
- A percent sign is shown in the table for health

# Screenshots

Before: 
Screenshot_20230602_211955
After:
Screenshot_20230602_212644
(Your emojis will probably look different)

# Storybook
## Before
[ManageCows](https://ucsb-cs156-s23.github.io/proj-happycows-s23-6pm-1/storybook/?path=/story/components-commons-managecows--uncontrolled)
[FarmStats](https://ucsb-cs156-s23.github.io/proj-happycows-s23-6pm-1/storybook/?path=/story/components-commons-farmstats--uncontrolled)
[ProfitsTable](https://ucsb-cs156-s23.github.io/proj-happycows-s23-6pm-1/storybook/?path=/story/components-commons-profitstable--emptytable)

## After
[ManageCows](https://ucsb-cs156-s23.github.io/proj-happycows-s23-6pm-1/prs/47/storybook/?path=/story/components-commons-managecows--uncontrolled)
[FarmStats](https://ucsb-cs156-s23.github.io/proj-happycows-s23-6pm-1/prs/47/storybook/?path=/story/components-commons-farmstats--uncontrolled)
[ProfitsTable](https://ucsb-cs156-s23.github.io/proj-happycows-s23-6pm-1/prs/47/storybook/?path=/story/components-commons-profitstable--emptytable)

Closes #39

### CODE REVIEW

**Comment by TheRealJBomb** [comment]
image

Note, you are not up-to-date with `main`. A fix was applied to fix this table overflow problem.

**Comment by TheRealJBomb** [comment]
Also, we don't want your changes to be overwritten by what Alex is doing in #29. You both may want to communicate with each other and add his additions into this PR.

**Review by joez-7 — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM!

**Pull request merged**
