### PR TITLE
Add different cow health update formulas, as a java enum

### LINKED ISSUE #14: Create strategy pattern for degradation formula
This issue is part of #10

Research and implement a strategy pattern for different options for degradation formula (Backend only, for now)

## Acceptance Criteria
- There is a strategy pattern (interface) for degradation update in the backend
- There are at least 2 implementations of the strategy (for testing)
- Strategy implementations can provide a user-friendly title and description
- There is a method for discovering all implemented strategies
- There is sufficient test coverage and tests pass

## Notes
- We can use Spring components for declaring/discovering implementations

### PR DESCRIPTION
**Pull request by GlassBricks**
In this PR, we introduce different possible formulas for cow health update.

This is a (imo) a much better alternative than #20. Java enums already support listing all values, getting by name, ordering, abstract methods, common fields, and JPA support... As such, all the functionality is done much more concisely, and in only one file. #20 has to do some weird tricks to achieve same thing.

Closes #14

### CODE REVIEW

**Review by mfletcher2 — APPROVED** [review]
LGTM

**Review by mfletcher2 — CHANGES_REQUESTED** [review]
nvm the test failed :skull:

**Comment by GlassBricks** [comment]
Pitest says the initial run failed without mutations, but the tests are clearly passing?

**Comment by GlassBricks** [comment]
So I just reran the action, and now it passes?

**Comment by GlassBricks** [comment]
I extracted the CowHealthUpdateStrategy to a separate interface, so that it can be mocked in (future) unit tests.

**Review by mfletcher2 — DISMISSED** [review]

**Comment by GlassBricks** [comment]
Discussion: what package should the new enum be in? It might make more sense for it to be in the `entity` package instead of `services`.

**Comment by briggsrrr** [comment]
> Discussion: what package should the new enum be in? It might make more sense for it to be in the `entity` package instead of `services`.

I definitely think this works as a service since there is no identity associated with the cow health strategies. Use of an enum (after some research...) is actually very clever. Will test and get back to you soon.

**Review by pconrad — APPROVED** [review]
LGTM... merge when green on CI

**Comment by albertyu03** [comment]
LGTM

**Review by albertyu03 — APPROVED** [review]
LGTM

**Review by mfletcher2 — APPROVED** [review]

**Pull request merged**
